/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spacetrade;

import engine.GameWindow;

public class App {
    
    public static void main(String[] args) {
        GameWindow window = GameWindow.getGameWindow();
        window.run();
    }
}
